websaya/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('class/<slug:cat>/<slug:detailview>', views.SingleView.as_view(), name='singleview'),
    path('class/<slug:catList>', views.CategoryView.as_view(), name='cat-list'),
    path('<slug:category>/<slug:detail>', views.SingleFunc, name='single'),
    path('<slug:catInput>/', views.CategoryIndexF, name='cat-index'),
    path('', views.IndexFunc, name='index'),
    path('classview', views.IndexView.as_view(), name='indexView'),
]

websaya/contact/urls.py
from django.urls import path

from . import views

app_name = 'Contact'
urlpatterns = [
    path('', views.KontakView, name='kontakForm'),
    path('list', views.KontakList.as_view(), name='kontakList'),
    path('add', views.ContactCreate.as_view(), name='add-contact'),
]

websaya/websaya/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include('contact.urls')),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websaya/blog/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Category(models.Model):
    category = models.CharField(max_length=25)
    slug_cat = models.SlugField(max_length=100, blank=True, unique=True)

    class Meta:
        ordering = ['-category']

    def save(self):
        self.slug_cat = slugify(self.category)
        super(Category, self).save()
    
    def __str__(self):
        return '{}'.format(self.category)

class Artikel(models.Model):
    from django.contrib.auth.models import User
    post_cat = models.ForeignKey(Category, to_field='slug_cat', on_delete=models.CASCADE)
    judul = models.CharField(max_length=75, unique=True)
    summary = models.TextField()
    body = models.TextField()
    date_create = models.DateField(auto_now_add=True)
    date_edit = models.DateField(auto_now=True)
    penulis = models.ForeignKey(User, to_field='username', null=True, blank=True, on_delete=models.CASCADE, related_name='author')
    publish = models.BooleanField(default=False)
    gambar = models.ImageField(upload_to='%Y/%m/%d', blank=True, null=True)
    slug = models.SlugField(max_length=175, unique=True, blank=True)

    class Meta:
        ordering = ['-date_create']
        permissions = {
            ('terbitkan', 'Terbikan Artikel')
        }
    
    def save(self):
        from django.utils import timezone
        self.slug = slugify(self.judul)
        super(Artikel, self).save()
    
    def __str__(self):
        return '{} | {} / {}'.format(self.id, self.judul, self.publish)

websaya/contact/models.py
from django.db import models

# Create your models here.
class Kontak(models.Model):
    nama_lengkap = models.CharField(max_length=70)
    tanggal_lahir = models.DateField()
    GENDER = [
        ('p', 'Pria'),
        ('w', 'Wanita'),
    ]
    jenis_kelamin = models.CharField(choices=GENDER, max_length=50)
    alamat = models.TextField()
    agree = models.BooleanField()

websaya/contact/forms.py
from django import forms
from django.forms import ModelForm
from .models import Kontak

class KontakForm(forms.Form):
    nama_lengkap = forms.CharField()
    tanggal_lahir = forms.DateField(
        required=False,
        widget=forms.SelectDateWidget(
            years=range(1930,2021),
            attrs={
                'class':'form-control col-sm-4'
            }
        )
    )
    GENDER = [
        ('p', 'Pria'),
        ('w', 'Wanita'),
    ]
    jenis_kelamin = forms.ChoiceField(choices=GENDER)
    alamat = forms.CharField(widget=forms.Textarea)
    agree = forms.BooleanField(required=False)

class ContactForm(ModelForm):
    class Meta:
        model = Kontak
        fields = '__all__'
        help_texts = {
            'tanggal_lahir': 'bulan/tanggal/tahun'
        }
        widgets = {
            'tanggal_lahir': forms.SelectDateWidget(
                years=range(1940,2021),
                attrs={
                    'class':'form-control col-sm-4'
                }
            )
        }
        labels = {
            'alamat': 'Alamat Lengkap'
        }

websaya/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Artikel, Category

# khusus function
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
# Function Based View
def IndexFunc(request):
    Post = Artikel.objects.filter(publish=True)
    page = request.GET.get('page', 1)
    paginator = Paginator(Post, 5)

    try:
        halaman = paginator.page(page)
    except PageNotAnInteger:
        halaman = paginator.page(1)
    except EmptyPage:
        halaman = paginator.page(paginator.num_pages)

    context = {
        'title': 'Latihan Membuat Blog',
        'deskripsi': 'Belajar django di Informatikawan',
        'posts': halaman,
    }
    return render(request, 'index.html', context)

def CategoryIndexF(request, catInput):
    Post = Artikel.objects.filter(post_cat=catInput, publish=True)
    page = request.GET.get('page', 1)
    paginator = Paginator(Post, 2)

    try:
        halaman = paginator.page(page)
    except PageNotAnInteger:
        halaman = paginator.page(1)
    except EmptyPage:
        halaman = paginator.page(paginator.num_pages)
    context = {
        'title': catInput,
        'posts': halaman,
    }
    return render(request, 'index.html', context)

def SingleFunc(request, category, detail):
    Post = Artikel.objects.get(slug=detail)
    #Categories = Artikel.objects.values('post_cat').distinct()
    Categories = Category.objects.all()
    context = {
        'posts': Post,
        'categories': Categories
    }
    return render(request, 'single.html', context)

# Class Based Views
class IndexView(ListView):
    queryset = Artikel.objects.filter(publish=True)
    paginate_by = 4

class CategoryView(ListView):
    paginate_by = 2

    def get_queryset(self):
        self.queryset = Artikel.objects.filter(publish=True, post_cat=self.kwargs['catList'])
        return super().get_queryset()

class SingleView(DetailView):
    def get_queryset(self):
        self.queryset = Artikel.objects.filter(slug=self.kwargs['detailview'])
        self.kwargs.update({
            'slug': self.kwargs['detailview']
        })
        return super().get_queryset()
    
    def get_context_data(self, *args, **kwargs):
        list_category = Category.objects.all()
        related_post = Artikel.objects.filter(publish=True, post_cat=self.object.post_cat)
        self.kwargs.update({
            'list_category': list_category,
            'related': related_post,
        })
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)

websaya/contact/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .forms import KontakForm, ContactForm
from .models import Kontak

# Create your views here.
def KontakView(request):
    contact_form = KontakForm(request.POST or None)
    if request.method == 'POST':
        if contact_form.is_valid():
            simpan_data = Kontak.objects.create(
                nama_lengkap = contact_form.cleaned_data.get('nama_lengkap'),
                jenis_kelamin = contact_form.cleaned_data.get('jenis_kelamin'),
                tanggal_lahir = contact_form.cleaned_data.get('tanggal_lahir'),
                alamat = contact_form.cleaned_data.get('alamat'),
                agree = contact_form.cleaned_data.get('agree')
            )
            return redirect('Contact:kontakList')
    context = {
        'title': 'Belajar Django',
        'kontak_saya': contact_form,
        'formulir': 'Class Form'
    }
    return render(request, 'contact/contact_form.html', context)

class KontakList(ListView):
    queryset = Kontak.objects.all()

class ContactCreate(SuccessMessageMixin, CreateView):
    form_class = ContactForm
    model = Kontak
    success_url = reverse_lazy('Contact:kontakList')
    success_message = 'Kontak berhasil disimpan'
    template_name = 'contact/contact_form.html'
    extra_context = {
        'kontak_saya': form_class,
        'formulir': 'Model Form'
    }

websaya/blog/templates/blog/artikel_detail.html
{% extends 'blog/snippets/base.html' %}

{% block pagetitle %}
<title>{{ object.judul }}</title>
<meta name="description" content="{{ object.summary }}">
{% endblock %}

{% block pagebody %}
<div class="row tm-row">
    <div class="col-12">
        <hr class="tm-hr-primary tm-mb-55">
        <!-- Video player 1422x800 -->
        <img src="{{ object.gambar.url }}" alt="{{ object.judul }}" style="width: 100%;">
    </div>
</div>
<div class="row tm-row">
    <div class="col-lg-8 tm-post-col">
        <div class="tm-post-full">                    
            <div class="mb-4">
                <h2 class="pt-2 tm-color-primary tm-post-title">{{ object.judul }}</h2>
                <p class="tm-mb-40">{{ object.date_create }}</p>
                {{ object.body|safe }}
                <span class="d-block text-right tm-color-primary">Kategori : <a href="{% url 'cat-list' catList=object.post_cat_id %}">{{ object.post_cat }}</a></span>
            </div>
            
            <!-- Comments -->
            <div>
                <h2 class="tm-color-primary tm-post-title">Comments</h2>
                <hr class="tm-hr-primary tm-mb-45">
                <div class="tm-comment tm-mb-45">
                    <figure class="tm-comment-figure">
                        <img src="img/comment-1.jpg" alt="Image" class="mb-2 rounded-circle img-thumbnail">
                        <figcaption class="tm-color-primary text-center">Mark Sonny</figcaption>
                    </figure>
                    <div>
                        <p>
                            Praesent aliquam ex vel lectus ornare tritique. Nunc et eros
                            quis enim feugiat tincidunt et vitae dui. Nullam consectetur
                            justo ac ex laoreet rhoncus. Nunc id leo pretium, faucibus 
                            sapien vel, euismod turpis.
                        </p>
                        <div class="d-flex justify-content-between">
                            <a href="#" class="tm-color-primary">REPLY</a>
                            <span class="tm-color-primary">June 14, 2020</span>
                        </div>                                                 
                    </div>                                
                </div>
                <div class="tm-comment-reply tm-mb-45">
                    <hr>
                    <div class="tm-comment">
                        <figure class="tm-comment-figure">
                            <img src="img/comment-2.jpg" alt="Image" class="mb-2 rounded-circle img-thumbnail">
                            <figcaption class="tm-color-primary text-center">Jewel Soft</figcaption>    
                        </figure>
                        <p>
                            Nunc et eros quis enim feugiat tincidunt et vitae dui.
                            Nullam consectetur justo ac ex laoreet rhoncus. Nunc
                            id leo pretium, faucibus sapien vel, euismod turpis.
                        </p>
                    </div>                                
                    <span class="d-block text-right tm-color-primary">June 21, 2020</span>
                </div>
                <form action="" class="mb-5 tm-comment-form">
                    <h2 class="tm-color-primary tm-post-title mb-4">Your comment</h2>
                    <div class="mb-4">
                        <input class="form-control" name="name" type="text">
                    </div>
                    <div class="mb-4">
                        <input class="form-control" name="email" type="text">
                    </div>
                    <div class="mb-4">
                        <textarea class="form-control" name="message" rows="6"></textarea>
                    </div>
                    <div class="text-right">
                        <button class="tm-btn tm-btn-primary tm-btn-small">Submit</button>                        
                    </div>                                
                </form>                          
            </div>
        </div>
    </div>
    <aside class="col-lg-4 tm-aside-col">
        <div class="tm-post-sidebar">
            <hr class="mb-3 tm-hr-primary">
            <h2 class="mb-4 tm-post-title tm-color-primary">Categories</h2>
            <ul class="tm-mb-75 pl-5 tm-category-list">
                {% for lc in list_category %}
                <li><a href="{% url 'cat-list' catList=lc.slug_cat %}" class="tm-color-primary">{{ lc.category }}</a></li>
                {% endfor %}
            </ul>
            <hr class="mb-3 tm-hr-primary">
            <h2 class="tm-mb-40 tm-post-title tm-color-primary">Related Posts</h2>
            {% for rp in related %}
            <a href="{% url 'singleview' cat=rp.post_cat_id detailview=rp.slug %}" class="d-block tm-mb-40">
                <figure>
                    {% if rp.gambar %}
                    <img src="{{ rp.gambar.url }}" alt="Image" class="mb-3 img-fluid">
                    {% endif %}
                    <figcaption class="tm-color-primary">{{ rp.judul }}</figcaption>
                </figure>
            </a>
            {% endfor %}
        </div>                    
    </aside>
</div>
{% endblock %}

websaya/blog/templates/blog/artikel_list.html
{% extends 'blog/snippets/base.html' %}

{% block pagetitle %}
<title>Edi Kartono | Artikel List</title>
<meta name="description" content="Belajar web framework django di informatikawan">
{% endblock %}

{% block pagebody %}
<div class="row tm-row">
{% for post in object_list %}
<article class="col-12 col-md-6 tm-post">
    <hr class="tm-hr-primary">
    <a href="{% url 'singleview' cat=post.post_cat_id detailview=post.slug %}" class="effect-lily tm-post-link tm-pt-60">
        {% if post.gambar %}
        <div class="tm-post-link-inner">
            <img src="{{ post.gambar.url }}" alt="{{ post.judul }}" class="img-fluid">                            
        </div>
        {% endif %}
        <span class="position-absolute tm-new-badge">New</span>
        <h2 class="tm-pt-30 tm-color-primary tm-post-title">{{ post.judul }}</h2>
    </a>                    
    <p class="tm-pt-30">
        {{ post.summary }}
    </p>
    <div class="d-flex justify-content-between tm-pt-45">
        <span class="tm-color-primary">{{ post.post_cat }}</span>
        <span class="tm-color-primary">{{ post.date_create }}</span>
    </div>
    <hr>
    <div class="d-flex justify-content-between">
        <span>36 comments</span>
        <span>by Admin Nat</span>
    </div>
</article>
{% endfor %}
</div>

{% if is_paginated %}
<div class="row tm-row tm-mt-100 tm-mb-75">
    <div class="tm-prev-next-wrapper">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="mb-2 tm-btn tm-btn-primary tm-prev-next tm-mr-20">Prev</a>
        {% else %}
        <a href="#" class="mb-2 tm-btn tm-btn-primary tm-prev-next disabled tm-mr-20">Prev</a>
        {% endif %}

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="mb-2 tm-btn tm-btn-primary tm-prev-next">Next</a>
        {% else %}
        <a href="#" class="mb-2 tm-btn tm-btn-primary disabled tm-prev-next">Next</a>
        {% endif %}
    </div>
    <div class="tm-paging-wrapper">
        <span class="d-inline-block mr-3">Page</span>
        <nav class="tm-paging-nav d-inline-block">
            <ul>
                {% for p in paginator.page_range %}
                {% if page_obj.number == p %}
                <li class="tm-paging-item active">
                    <a href="#" class="mb-2 tm-btn tm-paging-link">{{ p }}</a>
                </li>
                {% else %}
                <li class="tm-paging-item">
                    <a href="?page={{ p }}" class="mb-2 tm-btn tm-paging-link">{{ p }}</a>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
        </nav>
    </div>                
</div>
{% endif %}
{% endblock %}

websaya/blog/templates/blog/snippets/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block pagetitle %}
    <title>Edi Kartono</title>
    <meta name="description" content="">
    {% endblock %}
{% include 'blog/snippets/style.html' %}
</head>
<body>
	<header class="tm-header" id="tm-header">
        {% include 'blog/snippets/header.html' %}
    </header>
    <div class="container-fluid">
        <main class="tm-main">
            <!-- Search form -->
            <div class="row tm-row">
                <div class="col-12">
                    {% block page_header %}
                    <form method="GET" class="form-inline tm-mb-80 tm-search-form">                
                        <input class="form-control tm-search-input" name="query" type="text" placeholder="Search..." aria-label="Search">
                        <button class="tm-search-button" type="submit">
                            <i class="fas fa-search tm-search-icon" aria-hidden="true"></i>
                        </button>                                
                    </form>
                    {% endblock %}
                </div>                
            </div>            
            {% block pagebody %}
            
            
            <p>INi adalah page body block</p>
                           
            
            {% endblock %}            
            <footer class="row tm-row">
                <hr class="col-12">
                <div class="col-md-6 col-12 tm-color-gray">
                    Design: <a rel="nofollow" target="_parent" href="https://templatemo.com" class="tm-external-link">TemplateMo</a>
                </div>
                <div class="col-md-6 col-12 tm-color-gray tm-copyright">
                    Copyright 2020 Xtra Blog Company Co. Ltd.
                </div>
            </footer>
        </main>
    </div>
    
</body>
</html>

websaya/blog/templates/blog/snippets/header.html
<div class="tm-header-wrapper">
    <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
    </button>
    <div class="tm-site-header">
        <div class="mb-3 mx-auto tm-site-logo"><i class="fas fa-times fa-2x"></i></div>            
        <h1 class="text-center">Edi Kartono</h1>
    </div>
    <nav class="tm-nav" id="tm-nav">            
        <ul>
            <li class="tm-nav-item active"><a href="#" class="tm-nav-link">
                <i class="fas fa-home"></i>
                Blog Home
            </a></li>
            <li class="tm-nav-item"><a href="{% url 'Contact:kontakList' %}" class="tm-nav-link">
                <i class="fas fa-pen"></i>
                Kontak List
            </a></li>
        </ul>
    </nav>
    <div class="tm-mb-65">
        <a rel="nofollow" href="https://fb.com/templatemo" class="tm-social-link">
            <i class="fab fa-facebook tm-social-icon"></i>
        </a>
        <a href="https://twitter.com" class="tm-social-link">
            <i class="fab fa-twitter tm-social-icon"></i>
        </a>
        <a href="https://instagram.com" class="tm-social-link">
            <i class="fab fa-instagram tm-social-icon"></i>
        </a>
        <a href="https://linkedin.com" class="tm-social-link">
            <i class="fab fa-linkedin tm-social-icon"></i>
        </a>
    </div>
    <p class="tm-mb-80 pr-5 text-white">
        Xtra Blog is a multi-purpose HTML template from TemplateMo website. Left side is a sticky menu bar. Right side content will scroll up and down.
    </p>
</div>

websaya/blog/templates/blog/snippets/style.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static "fontawesome/css/all.min.css" %}"> <!-- https://fontawesome.com/ -->
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"> <!-- https://fonts.google.com/ -->
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static "css/templatemo-xtra-blog.css" %}" rel="stylesheet">
<!--

TemplateMo 553 Xtra Blog

https://templatemo.com/tm-553-xtra-blog

-->

websaya/contact/templates/contact/contact_form.html
{% extends 'blog/snippets/base.html' %}

{% load widget_tweaks %}

{% block page_header %}
<a href="{% url 'Contact:kontakForm' %}">Class Form</a> | <a href="{% url 'Contact:add-contact' %}">Model Form</a>
{% endblock %}

{% block pagebody %}
<h1>Membuat Form Dengan {{ formulir }}</h1>
<div class="row tm-row tm-mb-120">
    <div class="col-lg-7 tm-contact-left">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in kontak_saya %}
            <div class="form-group row mb-4">
                <label for="{{ field.auto_id }}" class="col-sm-3 col-form-label text-right tm-color-primary">
                    {{ field.label }}
                </label>
                <div class="form-row col-sm-9">
                    {{ field | add_class:"form-control mr-0 ml-auto" }}
                    <div class="form-row col-sm-9">
                        {{ field.help_text }}
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="form-group row text-right">
                <div class="col-12">
                    <button class="tm-btn tm-btn-primary tm-btn-small">Submit</button>                        
                </div>                            
            </div>
        </form>
    </div>

    <div class="col-lg-5 tm-contact-right">
        <address class="mb-4 tm-color-gray">
            120 Lorem ipsum dolor sit amet,
            consectetur adipiscing 10550
        </address>
        <span class="d-block">
            Tel:
            <a href="tel:060-070-0980" class="tm-color-gray">060-070-0980</a>
        </span>
        <span class="mb-4 d-block">
            Email:
            <a href="mailto:info@company.com" class="tm-color-gray">info@company.com</a>
        </span>
        <p class="mb-5 tm-line-height-short">
            Maecenas eu mi eu dui cursus
            consequat non eu metus. Morbi ac
            turpis eleifend, commodo purus
            eget, commodo mauris.
        </p>
        <ul class="tm-social-links">
            <li class="mb-2">
                <a href="https://facebook.com" class="d-flex align-items-center justify-content-center">
                    <i class="fab fa-facebook"></i>
                </a>
            </li>
            <li class="mb-2">
                <a href="https://twitter.com" class="d-flex align-items-center justify-content-center">
                    <i class="fab fa-twitter"></i>
                </a>
            </li>
            <li class="mb-2">
                <a href="https://youtube.com" class="d-flex align-items-center justify-content-center">
                    <i class="fab fa-youtube"></i>
                </a>
            </li>
            <li class="mb-2">
                <a href="https://instagram.com" class="d-flex align-items-center justify-content-center mr-0">
                    <i class="fab fa-instagram"></i>
                </a>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

websaya/contact/templates/contact/kontak_list.html
{% extends 'blog/snippets/base.html' %}

{% block page_header %}
<a href="{% url 'Contact:kontakForm' %}">Class Form</a> | <a href="{% url 'Contact:add-contact' %}">Model Form</a>
{% if messages %}
    {% for message in messages %}
    <span class="text-succes">{{ message }}</span>
    {% endfor %}
{% endif %}
{% endblock %}

{% block pagebody %}
<div class="row tm-row">
    {% for k in object_list %}
    <article class="col-12 col-md-6 tm-post">
        <hr class="tm-hr-primary">
        <a href="#" class="effect-lily tm-post-link tm-pt-60">
            <h2 class="tm-pt-30 tm-color-primary tm-post-title">Nama :{{ k.nama_lengkap }}</h2>
        </a>                    
        <p class="tm-pt-30">
            Alamat : {{ k.alamat }}
        </p>
        <div class="d-flex justify-content-between tm-pt-45">
            <span class="tm-color-primary">Jenis Kelamin</span>
            <span class="tm-color-primary">{{ k.jenis_kelamin}}</span>
        </div>
        <hr>
        <div class="d-flex justify-content-between">
            <span>Tanggal Lahir</span>
            <span>{{ k.tanggal_lahir }}</span>
        </div>
    </article>
    {% endfor %}
</div>
{% endblock %}